### ISSUE TITLE
Reduce the number of files in node_modules

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#212]
`find node_modules/ | wc -l`
29294

```
for i in * ; do echo $i `find $i |wc -l` ; done | sort -k2 -n
```

flying-squid.js 1
array-differ 4
array-uniq 4
assert-plus 4
bindings 4
co 4
diff 4
first-chunk-stream 4
get-stdin 4
slash 4
spdx-exceptions 4
spiralloop 4
ansi-regex 5
ansi-styles 5
array-find-index 5
asap 5
aws-sign2 5
babel-preset-es2015 5
babel-preset-stage-0 5
babel-preset-stage-1 5
babel-preset-stage-2 5
babel-preset-stage-3 5
beeper 5
boundary 5
camelcase 5
chalk 5
code-point-at 5
concat-stream 5
decamelize 5
domelementtype 5
emit-then 5
error-ex 5
escape-string-regexp 5
fancy-log 5
find-index 5
forever-agent 5
glob2base 5
glogg 5
has-ansi 5
has-gulplog 5
home-or-tmp 5
ini 5
irregular-plurals 5
is-builtin-module 5
is-finite 5
is-fullwidth-code-point 5
is-utf8 5
left-pad 5
load-json-file 5
lodash._basecallback 5
lodash._basecopy 5
lodash._baseeach 5
lodash._baseisequal 5
lodash._basereduce 5
lodash._basetostring 5
lodash._basevalues 5
lodash._bindcallback 5
lodash.escape 5
lodash._getnative 5
lodash.isarguments 5
lodash.isarray 5
lodash._isiterateecall 5
lodash.istypedarray 5
lodash.keys 5
lodash.pairs 5
lodash.reduce 5
lodash._reescape 5
lodash._reevaluate 5
lodash._reinterpolate 5
lodash.restparam 5
lodash._root 5
lodash.template 5
lodash.templatesettings 5
log-symbols 5
map-obj 5
npm-prefix 5
number-is-nan 5
object-assign 5
once 5
os-homedir 5
os-tmpdir 5
path-exists 5
path-is-absolute 5
path-type 5
pify 5
pinkie 5
pinkie-promise 5
plur 5
read-pkg 5
read-pkg-up 5
redent 5
regjsgen 5
repeat-string 5
shebang-regex 5
sparkles 5
spdx-correct 5
spdx-license-ids 5
string-width 5
strip-ansi 5
strip-bom 5
supports-color 5
tildify 5
time-stamp 5
to-fast-properties 5
trim-newlines 5
trim-right 5
tunnel-agent 5
untildify 5
validate-npm-package-license 5
wrap-fn 5
amdefine 6
assertion-error 6
attach-ware 6
bail 6
brace-expansion 6
ccount 6
clone-stats 6
collapse-white-space 6
combined-stream 6
commander 6
end-of-stream 6
event-promise 6
form-data 6
globals 6
gulplog 6
gulp-plumber 6
interpret 6
invariant 6
js-tokens 6
longest-streak 6
markdown-table 6
minimatch 6
oauth-sign 6
prismarine-item 6
qs 6
range 6
regenerate 6
repeating 6
spdx-expression-parse 6
string_decoder 6
strip-indent 6
strip-json-comments 6
structured-source 6
through2 6
to-vfile 6
trim-trailing-lines 6
unherit 6
unified 6
user-home 6
v8flags 6
vfile 6
vfile-reporter 6
vfile-sort 6
vinyl-sourcemaps-apply 6
ware 6
builtin-modules 7
defaults 7
findup-sync 7
flatmap 7
gaze 7
glob 7
graceful-readlink 7
growl 7
inflight 7
inherits 7
isarray 7
loud-rejection 7
ms 7
pretty-hrtime 7
process-nextick-args 7
require-self 7
sequencify 7
stream-consume 7
uint4 7
underscore 7
util-deprecate 7
wrappy 7
core-util-is 8
deep-extend 8
extend.js 8
fifo 8
graceful-fs 8
is-integer 8
loose-envify 8
node-promise-es6 8
orchestrator 8
parse-json 8
prismarine-windows 8
private 8
promise 8
regexpu-core 8
regjsparser 8
sigmund 8
trim 8
anchor-markdown-header 9
color-convert 9
esutils 9
he 9
is-arrayish 9
jsesc 9
mime 9
ordered-read-streams 9
prismarine-recipe 9
replace-ext 9
type-detect 9
unique-stream 9
buffer-equal 10
clone 10
concat-map 10
deprecated 10
endian-toggle 10
extend 10
line-numbers 10
markdown-to-ast 10
multipipe 10
node-dir 10
quotemeta 10
xtend 10
async 11
balanced-match 11
camelcase-keys 11
find-up 11
glob-watcher 11
gulp-babel 11
indent-string 11
json-stringify-safe 11
mojangson 11
tough-cookie 11
update-section 11
vinyl 11
yggdrasil 11
cryptiles 12
debug 12
rechoir 12
typedarray 12
archy 13
macaddress 13
prismarine-block 13
boom 14
lru-cache 14
prismarine-chunk 14
request 15
sntp 15
ctype 16
flagged-respawn 16
prismarine-nbt 16
dateformat 17
minimist 17
asn1 18
convert-source-map 18
deep-eql 18
entities 18
gulp-sourcemaps 18
ursa-purejs 18
hosted-git-info 19
liftoff 19
text-table 19
delayed-stream 20
domutils 20
hoek 20
node-uuid 20
source-map 20
uuid-1345 20
prismarine-world-sync 22
readable-stream 22
uuid 24
requireindex 25
semver 25
prismarine-entity 26
mkdirp 27
dom-serializer 28
duplexer2 28
detect-indent 30
hawk 30
http-signature 31
signal-exit 31
meow 34
domhandler 35
glob-stream 35
traverse 36
rc 39
diamond-square 40
gulp-util 40
node-rsa 40
normalize-package-data 40
gulp 42
doctoc 45
chai 47
yargs 47
nan 48
ursa 48
bluebird 49
deasync 56
mdast 56
source-map-support 70
longjohn 79
jade 81
vinyl-fs 83
globule 86
htmlparser2 87
minecraft-data 87
moment 112
minecraft-protocol 118
resolve 124
mocha 125
json5 153
babel-runtime 222
babel-helper-bindify-decorators 257
babel-helper-builder-binary-assignment-operator-visitor 257
babel-helper-call-delegate 257
babel-helper-explode-assignable-expression 257
babel-helper-explode-class 257
babel-helper-function-name 257
babel-helper-get-function-arity 257
babel-helper-hoist-variables 257
babel-helper-optimise-call-expression 257
babel-helper-remap-async-to-generator 257
babel-helper-replace-supers 257
babel-messages 257
babel-plugin-check-es2015-constants 257
babel-plugin-syntax-async-functions 257
babel-plugin-syntax-class-constructor-call 257
babel-plugin-syntax-class-properties 257
babel-plugin-syntax-decorators 257
babel-plugin-syntax-do-expressions 257
babel-plugin-syntax-exponentiation-operator 257
babel-plugin-syntax-export-extensions 257
babel-plugin-syntax-function-bind 257
babel-plugin-syntax-object-rest-spread 257
babel-plugin-transform-async-to-generator 257
babel-plugin-transform-class-constructor-call 257
babel-plugin-transform-class-properties 257
babel-plugin-transform-decorators 257
babel-plugin-transform-do-expressions 257
babel-plugin-transform-es2015-arrow-functions 257
babel-plugin-transform-es2015-block-scoped-functions 257
babel-plugin-transform-es2015-computed-properties 257
babel-plugin-transform-es2015-destructuring 257
babel-plugin-transform-es2015-for-of 257
babel-plugin-transform-es2015-function-name 257
babel-plugin-transform-es2015-literals 257
babel-plugin-transform-es2015-modules-commonjs 257
babel-plugin-transform-es2015-object-super 257
babel-plugin-transform-es2015-shorthand-properties 257
babel-plugin-transform-es2015-spread 257
babel-plugin-transform-es2015-sticky-regex 257
babel-plugin-transform-es2015-template-literals 257
babel-plugin-transform-es2015-typeof-symbol 257
babel-plugin-transform-es2015-unicode-regex 257
babel-plugin-transform-exponentiation-operator 257
babel-plugin-transform-export-extensions 257
babel-plugin-transform-function-bind 257
babel-plugin-transform-object-rest-spread 257
babel-plugin-transform-strict-mode 257
babel-helpers 258
babel-plugin-transform-runtime 258
babel-code-frame 259
babel-plugin-transform-es2015-parameters 260
babylon 260
babel-plugin-transform-es2015-classes 261
prismarine-world 265
babel-plugin-syntax-trailing-function-commas 274
babel-plugin-transform-regenerator 276
protodef 319
lodash 373
prismarine-provider-anvil 489
babel-helper-define-map 691
babel-helper-regex 691
babel-template 691
babel-plugin-transform-es2015-block-scoping 692
babel-register 696
babel-types 706
babel-generator 710
babel-core 722
babel-traverse 725
request-promise 895
core-js 908
mineflayer 967

come on.

**Comment by rom1504** [comment]
7599 excluding babel.

But I think the reason babel has some many files here, is because half the dependencies depend on babel-runtime 5 and the other on babel-runtime 6. npm3 is confused (and stupid, but we can't fix that)

**Comment by rom1504** [comment]
Also, lodash has too many files, I think we don't need it.

**Comment by rom1504** [comment]
(I'm sick of waiting 5min for flying-squid to install on my laptop)

**Comment by mhsjlw** [comment]
:+1:

**Comment by rom1504** [comment]
Needs babel6 updating:
* [x] protodef
* [ ] prismarine-world
* [ ] prismarine-provider-anvil
* [ ] what else ?

**Comment by roblabla** [comment]
Lodash has modules for every functions (e.g. : https://www.npmjs.com/package/lodash.map ). You could use that to reduce the deps.

**Comment by rom1504** [comment]
Yeah, protodef uses lodash.reduce which is okay because it's not completely trivial. But this https://github.com/PrismarineJS/mineflayer/commit/af51d44f6b3b913859850c5e36e957e59954a14c wasn't worth it.

**Comment by roblabla** [comment]
Heh, and the new code is cleaner too :P

**Comment by mhsjlw** [comment]
Shouldn't mineflayer only be downloaded during tests? By default we should disable it from being downloaded unless it's a CI or a crazy person who wants to use the tests

**Comment by rom1504** [comment]
@mhsjlw yes it's only downloaded for dev. So is babel and gulp.

But I am a dev, and I don't want 30k files on my node_modules.

**Comment by rom1504** [comment]
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-block-scoping/package.json#L13 WTF

**Comment by rom1504** [comment]
so, well, updating to babel6 didn't help because babel6 depends on babel-runtime5
whatever.

**Comment by rom1504** [comment]
Well I'm down to 28360, I guess that's something

**Comment by javacoolme** [comment]
[This](http://npm.anvaka.com/#/view/2d/flying-squid) might help a bit...

**Comment by javacoolme** [comment]
I've submitted some issues in this and other repositories to help get this done:
[Use phin instead of request](https://github.com/zekesonxx/node-yggdrasil/issues/22)
[Use uuid instead of node-uuid](https://github.com/PrismarineJS/flying-squid/issues/308) (some other package depends on [`uuid`](https://npmjs.com/package/uuid), so this just drops one dependency).
[Switch from uuid-1345 to uuid](https://github.com/PrismarineJS/node-minecraft-protocol/issues/515) (again, some other package in this repository depends on [`uuid`](https://npmjs.com/package/uuid))

**Comment by javacoolme** [comment]
Also, we should switch from [`request`](https://npmjs.com/package/request) to [`phin`](https://npmjs.com/package/phin).

[`request`](https://npmjs.com/package/request) is huge and has way to many dependencies. Use [`phin`](https://npmjs.com/package/phin) instead!

See the difference between [`request`](http://npm.anvaka.com/#/view/2d/request) and [`phin`](http://npm.anvaka.com/#/view/2d/phin) on [npm.anvaka.com](https://npm.anvaka.com).

**Comment by MTRNord** [comment]
Also using yarn instead npm will speed up the download as yarn uses multiple requests at the same time. Npm only runs 1 after each other. :)

**Comment by javacoolme** [comment]
@MTRNord even NPM 5?

**Comment by MTRNord** [comment]
@javacoolme not sure but yarn (personal opinion) still feels faster.

**Comment by javacoolme** [comment]
@rom1504 why do devs need `babel-...`? Just curious...

**Comment by roblabla** [comment]
We could probably remove babel anyway. NMP doesn't use it anymore.

**Comment by roblabla** [comment]
Concerning `phin`, I think it'd be very much appreciated if @javacoolme or someone else submitted a PR to `node-yggdrasil` and this project to replace requests with `phin`. Besides, it's probably a fairly good, easy way to get to know the code :)

**Comment by javacoolme** [comment]
@roblabla I'll get on it at some point! Will remove babel as well to see what that does.

**Comment by rom1504** [comment]
not sure what everybody is worried about that issue (and flying squid) now, but current flying-squid state is at https://github.com/PrismarineJS/flying-squid/pull/286 and babel is indeed gone

**Comment by javacoolme** [comment]
@rom1504 Oh, awesome

Can you check how many files there are now?

**Comment by rom1504** [comment]
5941

I guess I'll try and finish that pr if you're interested in flying-squid

**Comment by rom1504** [comment]
worth noting npm 5 takes 12s to `npm install` now
it used to take several minutes (maybe 3 ? I don't remember exactly) to install everything

**Comment by javacoolme** [comment]
@rom1504 19s for me, on hotel Wi-Fi, still a very large improvement, though. I'll be making a pull request in a bit to get this even faster.

Also, I didn't even install dev dependencies and running `find node_modules/ | wc -l` gave me `9452`.

**Comment by rom1504** [comment]
I'm talking about https://github.com/PrismarineJS/flying-squid/pull/286

if you are going to make a PR, it should be based on that branch https://github.com/rom1504/flying-squid/tree/1_9

**Comment by javacoolme** [comment]
@rom1504 Ah, understood. Thanks.

**Comment by mhsjlw** [comment]
Planning on switching to Yarn. Allows for dependencies to be cached. Planning on switching test suite to Jest as well. Will await your PR @javacoolme

**Comment by javacoolme** [comment]
@mhsjlw @rom1504 Created the PRs! See [the `flying-squid` PR](https://github.com/rom1504/flying-squid/pull/1) and [the `node-yggdrasil` PR](https://github.com/zekesonxx/node-yggdrasil/pull/23).

**Comment by mhsjlw** [comment]
yarn (among other things) has been added to rom's PR

**Comment by zekesonxx** [comment]
node-yggdrasil v1.1.0 has changed to phin (courtesy of @bdsomer) dropping it's dep count to 2.

**Comment by mhsjlw** [comment]
Perhaps I'm just crazy, but what the heck is removing `request` from a couple of modules going to do?

From the original snippet, `request 15`, means `request` is being used 15 times. How will switching to `phin` help us if npm will automatically link other module's `request` to our requirement on `request`?

**Comment by mhsjlw** [comment]
Additionally, `phin`'s license is non-SPDX citing "SEE LICENSE IN LICENSE.md" which leads me to some [omnent-licenses](https://github.com/omnent/omnent-licenses) repository. Not sure I want to use a module that has fuzzy licensing like that in flying-squid.

**Comment by bdsomer** [comment]
Pinging @ethanent

**Comment by ethanent** [comment]
@mhsjlw @bdsomer Thanks for the mention & question!

The OMv2-FO license is heavily based on the MIT License. Feel free to read over it for yourself, of course! https://github.com/omnent/omnent-licenses/blob/master/licenses/OMv2-FO.txt

**Comment by rom1504** [comment]
I think that issue could be closed now. We got rid of Babel and install is fast enough.

**Comment by bdsomer** [comment]
Agreed @rom1504

**Comment by mhsjlw** [comment]
Also-- forgot the post this, but using the command that @rom1504 gave at the start, the original value before removing babel and friends was:`29294` it is now: `11141`
