### ISSUE TITLE
1.12.2 Protocol Support

### ISSUE THREAD

**Issue by mhsjlw** [PrismarineJS/flying-squid#219]
See 1.12.2 milestone

**Comment by rom1504** [comment]
first step is at https://github.com/PrismarineJS/prismarine-chunk/issues/19

**Comment by mhsjlw** [comment]
Okey dokey. So here's a list of things that I've found we need to fix so far:

- placeBlock is broken because now in 1.12.2, the client doesn't send us the block with the placeBlock, they actually send us their hand (which we then need to resolve to the item)-- not entirely sure how to add this since we don't really have a way to get this right now (that I know of)
- Sending entity positions to players (i.e.: players can't see each other right now)-- I think this is just some scaling stuff we have to fix (it appears the `/ 32` works for sending the player theirself's position)
- etc.

**Comment by rom1504** [comment]
Yes entities position format has changed
