### ISSUE TITLE
Cannot run commands as server

### ISSUE THREAD

**Issue by javacoolme** [PrismarineJS/flying-squid#234]
https://github.com/PrismarineJS/flying-squid/blob/master/doc/API.md#methods

There is no "executeCommand" method or anything similar.

**Comment by mhsjlw** [comment]
development for a server command prompt in dazed-sheep has started, once it's completed it could be merged into flying-squid. it'd probably be better to separate it into a module though

**Comment by FuturisticCake** [comment]
flying-squid's main purpose is not to be an executable MC server. Its purpose is to provide an API to build servers with.

Therefore, this is an invalid issue.

**Comment by mhsjlw** [comment]
well... it does raise an important issue? do we want to aim to just be an API, or do we want to be a proper minecraft server executable. when i originally created the server software, i more thought of it as an API which is why rom and i built it this way. let me know what you think. if not, we could still implement this as a plugin

**Comment by rom1504** [comment]
flying-squid is both a lib and a server.
It's quite fine for contributors to focus on one of the other side of the project depending on their interest though ;)

**Comment by javacoolme** [comment]
Sorry for responding to this so late.

The question was not worded well and has been updated. See the new post.

**Comment by mhsjlw** [comment]
Hello! I think as far as executeCommand goes, first we actually have to implement that API... are you looking for an API like the player commands but instead for the server? I'm still a little bit unclear... the executeCommand still needs some sort of backend for plugins to implement.

**Comment by javacoolme** [comment]
Here, some examples:

```javascript
server.executeCommand('ban Notch'); // Bans 'Notch' from the game
server.executeCommand('say Hello!'); // Sends '[Server] Hello!' to the chat
server.executeCommand('setblock 10 10 10 stone'); // Sets the block at 10, 10, 10 to stone.
```

**Comment by mhsjlw** [comment]
Yeah, yeah, I get that part. I'm saying that we've got to decide how we're going to implement this. Do we want the player command API to be merged with a server command API and just have them together? Or do we want to implement a *new* API for plugins (and the server itself) adding commands to the server

**Comment by javacoolme** [comment]
> Do we want the player command API to be merged with a server command API and just have them together?

That sounds best.

> Or do we want to implement a new API for plugins (and the server itself) adding commands to the server

That sounds like a lot of code duplication. Example: Microsoft goes and decides to change the `setblock` command to do something else. Instead of having to update that in one place, we now have to update that command when running as server and when running as player.
