### ISSUE TITLE
Server maxPlayers option value does not change ping max-player value

### ISSUE THREAD

**Issue by FuturisticCake** [PrismarineJS/flying-squid#235]
When pinging a flying-squid server from the multiplayer server list, the server will always be shown with a max-player count of 20.

**Comment by rom1504** [comment]
even if you change https://github.com/PrismarineJS/flying-squid/blob/master/config/default-settings.json#L4 ?

**Comment by rom1504** [comment]
The options is `max-players` not `maxPlayers`

**Comment by FuturisticCake** [comment]
Woah, can't believe I missed that! Thanks :)

I seem to keep misreading the docs!
