### ISSUE TITLE
Tell me please, the server running now to the specified address, is it flying-squid?

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/flying-squid#311]
rom1504.fr:25565
Good afternoon. Tell me please, the server running now to the specified address, is it flying-squid?

**Comment by mhsjlw** [comment]
Yeah, it's our test server

**Comment by lastuniverse** [comment]
But in this server there are:
Spawn mobs with AI;
planting of vegetation, its growth;
crafting and achievements;
Etc.

Truth is all reset at death and / or exit from the game. And also partially build buildings.

But judging by this server, your progress is colossal !!!


Question: the server downloaded from here (https://github.com/PrismarineJS/flying-squid) does not even have half of these features (

**Comment by rom1504** [comment]
fixed

**Comment by lastuniverse** [comment]
This topic can be completely closed (or deleted). I wrote my questions here because I did not know how else to contact you.
