### ISSUE TITLE
How can I do to translate documents?

### ISSUE THREAD

**Issue by Shin-JaeHeon** [PrismarineJS/flying-squid#312]
How can I do to translate documents?

**Comment by rom1504** [comment]
what is a document ?

**Comment by Shin-JaeHeon** [comment]
It is a api.md or history.md or etc.

**Comment by rom1504** [comment]
Oh, you can propose a api-kr.md in a pull request if you want.

**Comment by mhsjlw** [comment]
See #313, not directly related but stems from the same idea

**Comment by Shin-JaeHeon** [comment]
@mhsjlw It's good idea.

**Comment by mhsjlw** [comment]
I think this is good to close since your question was answered
