### ISSUE TITLE
Fix master

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#321]
master has been "updated" to 1.12 but actually it doesn't work

options : 
1. fixing master to fully support 1.12
2. making a 1.8 branch starting from a few commits back to have at least one working branch

**Comment by rom1504** [comment]
Also it would be nice to take most of my commits from https://github.com/PrismarineJS/flying-squid/pull/286/commits , they mostly make switching version easier

**Comment by rom1504** [comment]
Well actually I think we're mostly missing https://github.com/PrismarineJS/flying-squid/pull/286/commits/f380e075430321a1b8e7eb62f389a5871dc99d99

**Comment by mhsjlw** [comment]
I never added 1.12 support in master, and it works fine when I connect from a 1.8 client?
