### ISSUE TITLE
Question for futur

### ISSUE THREAD

**Issue by SecretsMan** [PrismarineJS/flying-squid#328]
Hello,

The project is still active? I plan to eventually make a server via prismarine

I would also like to know if you were going to do a typescript definition file?

**Comment by SecretsMan** [comment]
Thank you for your reply..

However I have not really succeeded unfortunately .. I just have a start of file if you wish: https://hastebin.com/gohidogaye.cs

**Comment by rom1504** [comment]
flying-squid is mostly plugin based though, so I'm pretty sure it's basically not possible to create typescript definition for the plugins.

javascript cannot really be typed...

**Comment by mhsjlw** [comment]
Especially our event emitter, that would be tedious to type, if it is even possible.

**Comment by SecretsMan** [comment]
I understand :)

I have other quesitons, I would like to know why you do not open a community discord for example?

And something else, why it is impossible to connect to the server to pars in 1.8 while it is noted 1.12.2 on the list of servers

**Comment by rom1504** [comment]
We have https://gitter.im/PrismarineJS/flying-squid for chat.

1.12 is definitely not supported, we are still at 1.8 currently (though it might not require a lot of work to do the migration, but it is not done)

**Comment by rom1504** [comment]
answered, now talking in the chat
