### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SecretsMan** [PrismarineJS/flying-squid#337]
How install flying-squid on windows ? ( i have error with github. )

**Comment by rom1504** [comment]
You're going to have to be more precise if you want answers...
What error do you have ?

**Comment by rom1504** [comment]
1) install node cygwin and git

2)
git clone git@github.com:PrismarineJS/flying-squid.git
cd flying-squid
npm install
node app.js
run the minecraft client
Connect to localhost:25565
Play.

**Comment by SuperOP535** [comment]
why cygwin

**Comment by rom1504** [comment]
Because windows command line is bad
