### ISSUE TITLE
support 1.13

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#341]
almost out, let's do it now

**Comment by demipixel** [comment]
Could we get a list of things required to make this happen? minecraft-protocol supports 1.13 but are there any other libraries that need to be updated?

**Comment by rom1504** [comment]
Yes. Main blocker since the beginning is prismarine-chunk.
We need a clean and working implementation of it for 1.13.
The one we have currently is broken.

I think the best way to solve that issue is to create a new implementation from scratch following the wiki.vg chunk doc.

You can give it a try if you want :)

**Comment by Saiv46** [comment]
Is prismarine-chunk is working now?

**Comment by dada513** [comment]
any progress?

**Comment by brettz9** [comment]
Looks like https://github.com/PrismarineJS/prismarine-chunk/issues/57 was closed, so I guess there are no more blockers?

(Btw, I'm new to even Minecraft, let alone this project, but just curious if I could introduce my son more to programming by getting a working server going, and possibly helping out along the way if I can figure things out and as opportunity permits.)

**Comment by rom1504** [comment]
Yeah we updated mineflayer to 1.13 recently. There is a merged PR that does
it.
We could apply the same kind of things to flying-squid to add 1.13 support

**Comment by rom1504** [comment]
mineflayer now supports 1.13, 1.14 and 1.15
all dependent packages support these version (and flying-squid use them)
we could try to bring support to flying-squid too

these PRs will probably be useful examples for this : 
* https://github.com/PrismarineJS/mineflayer/pull/712 1.13
* https://github.com/PrismarineJS/mineflayer/pull/968 1.14
* https://github.com/PrismarineJS/mineflayer/pull/980 1.15

I suggest doing it version by version, that strategy did make it much easier for mineflayer

**Comment by rom1504** [comment]
not sure if I will be working on this, but if anyone is motivated to start something, I can help out

**Comment by rom1504** [comment]
mostly done

last stuff to fix there https://github.com/PrismarineJS/flying-squid/issues/416
