### ISSUE TITLE
setup discord/irc/gitter bot

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#350]
https://github.com/reactiflux/discord-irc

**Comment by mhsjlw** [comment]
We should link the discord in the README to populate it, and we should note it in the Gitter. It might be a better idea to create a flying squid discord plugin. I'd be willing to do that.

**Comment by rom1504** [comment]
I want a bridge before putting it on the README.
depending on flying-squid to do the bridging is a bit risky
and also it doesn't make sense for (prismarine) gitter room other than flying-squid

**Comment by CertainLach** [comment]
I have bot that has support for both Discord/IRC/Telegram/some another messagers: http://github.com/Certainlach/Ayzek, but he needs more active support, because i have no time to maintain them;

**Comment by CertainLach** [comment]
But for bridge, xbot should be better choose :D 
https://github.com/CertainLach/Framework/blob/master/packages/xbot/index.ts
This is just a combiner for adapters, which emits message events:
https://github.com/CertainLach/Framework/tree/master/packages/xbot/api

**Comment by CertainLach** [comment]
(Just advertise ,ine development, in the hope that they will be useful at least to someone other than me)

**Comment by mhsjlw** [comment]
Went with matterbridge. Configuration here: https://gist.github.com/mhsjlw/8b2bb3af93249880717cdbc564d4cd44

**Comment by rom1504** [comment]
nice :+1:
