### ISSUE TITLE
Registering Plugins

### ISSUE THREAD

**Issue by ConorTheDev** [PrismarineJS/flying-squid#360]
I want to know how I register my plugins, this is what my folder structure looks like:
![image](https://user-images.githubusercontent.com/31479541/51802312-c29f9380-2240-11e9-851d-5edb19cdd699.png)

My code for my server.js:

```js
const mcServer = require('flying-squid')

mcServer.createMCServer({
    'motd': 'account.conorthedev.club | Authentication Server',
    'port': 25565,
    'max-players': 10,
    'online-mode': true,
    'logging': true,
    'gameMode': 1,
    'difficulty': 1,
    'worldFolder': 'world',
    'generation': {
        'name': 'diamond_square',
        'options': {
            'worldHeight': 80
        }
    },
    'kickTimeout': 10000,
    'plugins': {

    },
    'modpe': false,
    'view-distance': 10,
    'player-list-text': {
        'header': 'Flying squid',
        'footer': 'Test server'
    },
    'everybody-op': false,
    'max-entities': 100,
    'version': '1.8.9'
})
```

My plugin code:
```js
var server = require("../../../server.js");

module.exports.player = function (player, serv) {
    console.log("haha yeet 1");
    player.on('spawned', () => {
        console.log("haha yeet 2");
        var authcode = server.makeid(event.player);
        player.kick("§aYour auth code is: §2" + authcode);
        server.authcodes.set(authcode, player);

        console.log(server.authcodes.entries())
    })
}
```
My plugin doesn't output "haha yeet 1" or "haha yeet 2" in console, so I believe it is not registering.

**Comment by rom1504** [comment]
here's the doc to create a plugin https://github.com/PrismarineJS/flying-squid/blob/master/docs/CONTRIBUTE.md#creating-external-plugins

**Comment by ConorTheDev** [comment]
I want to do internal in server I don't want everyone having my plugin src as it contains sensitive info if I make it external

**Comment by rom1504** [comment]
so read the second part https://github.com/PrismarineJS/flying-squid/blob/master/docs/CONTRIBUTE.md#testing-your-plugin ?

however "it contains sensitive info" is a bad idea.

**Comment by ConorTheDev** [comment]
i really dont think you're getting at what i'm trying to say here.


I want to test my plugin without having to publish it, can you tell me how to do this as your guide doesn't tell me shit

**Comment by Himself65** [comment]
and I'm trying to fix it

**Comment by Himself65** [comment]
@ConorTheDev @rom1504 
I think the wrong thing is that we do not import third-party plugins at all.

and I have fixed it on #359

**Comment by rom1504** [comment]
it's already done at https://github.com/PrismarineJS/flying-squid/blob/e28e5b0e6285eed30720c214120d021ac8f52b91/src/lib/plugins/external.js

**Comment by Himself65** [comment]
@ConorTheDev 
like this #361
