### ISSUE TITLE
Don't generate world if already generated or imported.

### ISSUE THREAD

**Issue by Vista1nik** [PrismarineJS/flying-squid#370]
Hey! Add option to disable generation if world folder already contain a world!

**Comment by rom1504** [comment]
You want to have empty chunks on the border of the existing world ? Feel free to add an empty generator then

**Comment by jcyh0120** [comment]
How can I import a world I made in single player mode?

**Comment by rom1504** [comment]
You can add it in the config, I believe there's an example in the current
config file

**Comment by jcyh0120** [comment]
Thanks! I thought the world is always generated. ( I misunderstood this issue)

I just change the worldFolder and it works!
Thanks again~

**Comment by Vista1nik** [comment]
Getting 
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'seed' of undefined
```
when importing external world.

**Comment by rom1504** [comment]
Did you define the seed property in the config ?
