### ISSUE TITLE
Bad packet id 84

### ISSUE THREAD

**Issue by zRattly** [PrismarineJS/flying-squid#372]
![image](https://user-images.githubusercontent.com/40183121/66403566-132dda00-e9e7-11e9-892d-ee24dd5fc7e6.png)

Hosting on Glitch.com

**Comment by rom1504** [comment]
Version 1.12.2 ?

**Comment by zRattly** [comment]
Yes

**Comment by rom1504** [comment]
In what case ?

**Comment by ooodlllars** [comment]
same

**Comment by rom1504** [comment]
Try to host it locally

**Comment by zRattly** [comment]
cant

**Comment by rom1504** [comment]
Ok can't help then
