### ISSUE TITLE
Spawn eggs when used cause server crash

### ISSUE THREAD

**Issue by cybertelx** [PrismarineJS/flying-squid#375]
When I used a spawn egg to try to spawn a mob, the server crashed with an error and my client disconnected.

**How to reproduce**
Self-explanatory.

**Version**
MC 1.12.2, flying-squid 1.1.2, node 12.9.1

**Comment by Karang** [comment]
@rom1504 this could be closed as it is fixed by https://github.com/PrismarineJS/flying-squid/pull/363
