### ISSUE TITLE
Figure out how to provide the "real position" of entities in the API

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#40]
Currently entity.position is in the fixed point format which is position*32.

Possible solutions : 
1. have both a entity.fixedPosition and a entity.position and update both when needed
2. keep entity.position as the fixed point number and make a entity.normalPosition() method

I think 1 is probably the more practical solution, but it means we probably need a entity.setPosition method to do the updating (so we don't have to convert manually every time we need to update the position)

**Comment by demipixel** [comment]
In essence, my vote was to do the opposite of #1 (entity.realPosition and entity.position). Otherwise I recommend like entity.getPosition() or something.

**Comment by demipixel** [comment]
Exactly 2 months and we still have this problem....
