### ISSUE TITLE
Check usage of prismarine-chunk by flying-squid is fast

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#406]
I have a suspicion we're using slow things.

**Comment by Karang** [comment]
Where ? I tested a bit of redstone and water (to generate loads of block updates) and everything seems fine.

**Comment by rom1504** [comment]
Ah, mostly generation and chunk loading, when doing tons of set block.
It seems slower than before on my computer, but it's just a suspicion, I did not measure anything
