### ISSUE TITLE
Fix a few remaining 1.13 issues

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#416]
Noticed issues :

* [ ] no clear error for incorrect saved world version (not blocking)
* [x] block dug drop is broken (go to /gamemode 0 to test)
* [x] dropping an item from hotbar (press q) crash the server
* [x] portal is using incorrect blocks (can be tested with the /portal command)

**Comment by Karang** [comment]
The broken drop is not specific to 1.13, and you can test it in creative by pressing the drop key (q)

Dropping should be handled in https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/plugins/digging.js#L8 (status 4)
All versions >= 1.8 should be the same: https://wiki.vg/index.php?title=Protocol&oldid=7368#Player_Digging

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/flying-squid/blob/303ad467c987487b2f2b46d89e89dc5cf9bb01e3/src/lib/plugins/digging.js#L134

it is handled, but crashing the server in 1.13

**Comment by rom1504** [comment]
ah I see, you're saying the server is sending us that status == 4 in all cases ?
then it's handled incorrectly indeed
it used to work (even if not vanilla then) for 1.8 and 1.12

**Comment by Karang** [comment]
Mmm wait, are we talking about the same thing ? I'm talking about when you drop an item from your inventory. Are you talking about the block that drop when you break a block ?

**Comment by rom1504** [comment]
ah, yes I was talking about drop when breaking a block, not inventory

**Comment by rom1504** [comment]
Done, moving last point to https://github.com/PrismarineJS/flying-squid/issues/421
