### ISSUE TITLE
Finish fixing portals for 1.13

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#423]
Observed now : 
1. /portal produces a correct portal
2. flint and steel works
3. a few blocks inside the portal do net let the player pass through (wrong state ?)
4. no change world happening

**Comment by Karang** [comment]
I think 3/4 were never implemented, I can't find anywhere in the code the logic for portal collision detection + world transfer.

I think a prerequist for that is to have prismarine-physics and use it. Then it becomes trivial to test the collision between players and portal blocks.

**Comment by rom1504** [comment]
ah yeah you're completely right. Not sure why I was convinced of the opposite :) 
https://github.com/PrismarineJS/flying-squid/issues/79 is the issue that track this.

/changeworld used to work though https://github.com/PrismarineJS/flying-squid/issues/424
