### ISSUE TITLE
Cannot read plugins.

### ISSUE THREAD

**Issue by quartze** [PrismarineJS/flying-squid#428]
Server can't get plugins from locations:
`./plugins/myplugin.js`, `./lib/plugins/myplugin.js`, `./src/lib/plugins/myplugin.js`.
I getting always the same output:
```
throw new Error('Cannot find plugin "' + p + '"')

Error: Cannot find plugin "myplugin"
```

Any idea how locations work in flying-squid?

**Comment by demipixel** [comment]
Have you tried `./src/plugins/myplugin/index.js`?

**Comment by quartze** [comment]
@demipixel yeah, still cannot find plugin.

**Comment by demipixel** [comment]
Does anything in [this issue](https://github.com/PrismarineJS/flying-squid/issues/366) help?

I mean [here's](https://github.com/PrismarineJS/flying-squid/blob/e28e5b0e6285eed30720c214120d021ac8f52b91/src/lib/plugins/external.js#L27) the line of code that tries to load the plugin—you can see exactly where it's trying to load from.

**Comment by quartze** [comment]
Not exactly, i get only the main plugin where this function is.
```
 at F:\files\MinecraftProject\node_modules\flying-squid\src\lib\plugins\external.js:29:15
    at Array.forEach (<anonymous>)
    at Object.module.exports.server (F:\files\MinecraftProject\node_modules\flying-squid\src\lib\plugins\external.js:21:33)
    at F:\files\MinecraftProject\node_modules\flying-squid\src\index.js:48:50
    at Array.forEach (<anonymous>)
    at MCServer.connect (F:\files\MinecraftProject\node_modules\flying-squid\src\index.js:48:8)
    at Object.createMCServer (F:\files\MinecraftProject\node_modules\flying-squid\src\index.js:27:12)
    at Object.<anonymous> (F:\files\MinecraftProject\server\server.js:4:23)
```

**Comment by redcarti** [comment]
If you using flying-squid as lib, plugins will not load (as I remember). They will be loaded if you clone repo

**Comment by redcarti** [comment]
> If you use it as a lib you can use give it the plugins packages

**Comment by quartze** [comment]
So i need to remove node_modules and install it again with plugins in main folder?

**Comment by rom1504** [comment]
No, can you either :
* Make your plugins packages
* Import your plugins using the load function

If none work, fix the code of flying-squid so it's possible for you to use
it as a lib with your plugins

**Comment by quartze** [comment]
Plugins packages doesnt work.

How to use it with lib?

**Comment by rom1504** [comment]
Could you try to fix it ?

**Comment by quartze** [comment]
I create new init with install only flying-squid and still nothing.

**Comment by rom1504** [comment]
I mean fix it inside flying-squid

**Comment by quartze** [comment]
I tried something, installed flying-squid command and start server with flying-squid command.
I got
```
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
```
