### ISSUE TITLE
1.16.1 Destroying block in survival crashes the server

### ISSUE THREAD

**Issue by tumenor** [PrismarineJS/flying-squid#436]
TypeError: Cannot read property 'name' of undefined
    at MCServer.serv.spawnObject (src\lib\plugins\spawn.js:39:37)

minecraft-data dependency seem to not have the objects for this version

**Comment by danielpmc** [comment]
Any idea if this is going to be fixed soon? im having the same issue lmao

**Comment by bitknox** [comment]
This is caused by minecraft-data incorrectly labeling every entity as a mob from 1.11 and up.  See https://github.com/PrismarineJS/minecraft-data/issues/341

**Comment by Creeper09** [comment]
so how do we fix it?
or do we just need to wait for flying squid to be updated?

**Comment by rom1504** [comment]
fixed now
