### ISSUE TITLE
i found this funny but it is indeed an issue so im going to place it here.

### ISSUE THREAD

**Issue by voizuu** [PrismarineJS/flying-squid#441]
https://i.gyazo.com/2cba9ee3fa2a3ca4d5f7c0e336244897.mp4

**Comment by Faris90** [comment]
Mineblox

**Comment by uAliFurkanY** [comment]
more information please, just a video will only inform us that it can do that

**Comment by voizuu** [comment]
it just happened when I made the server, I don't really know if I can replicate it if it doesn't happen to other people/.

**Comment by rom1504** [comment]
no information here, reopen if you want to ask something
