### ISSUE TITLE
Is there a way to use proxy like bungeecord using Flying Squid?

### ISSUE THREAD

**Issue by wh1teskyy** [PrismarineJS/flying-squid#444]
I dont know even a little bit of Java, and i ever wanted to make my own minigames server with my own plugins, and i found Flying Squid, but i wanna know if there's a way to teleport users though servers like in bungeecord. Thank you!

**Comment by TheAlan404** [comment]
I found how we can do it!

https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/

Plugin channels was recently added to flying-squid/nmp so its gonna be.. easy..?
When I'm home I'll try to make this, its a good idea, for now I'll read the docs and try to figure out how it exactly works

**Comment by KaffinPX** [comment]
You can do it easily with bungeecord proxy feature, only start bungeecord and write flying-squids ip.
