### ISSUE TITLE
1.12.2 - Chunks are (still) broken

### ISSUE THREAD

**Issue by TheAlan404** [PrismarineJS/flying-squid#467]
It doesnt send any chunks... node v14 superflat generator, doesnt work with other generators too

**Comment by TheAlan404** [comment]
ok nvm i fixed it, reminder: "view-distance" is NOT optional

also documenting all of the server settings would be a good idea i guess

**Comment by rom1504** [comment]
If you can document anything that was missing for you, it would be useful
for the next person
