### ISSUE TITLE
Guaranteed way to lose your player save file

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/flying-squid#484]
basically if you send a misshaped packet (in testing, what was breaking my saves was the declare_commands packet) then try to join, you will get a gson error. restart the server, join without that line of code and you lose your save file!

**Comment by TheAlan404** [comment]
Can you explain a bit more?

**Comment by u9g** [comment]
I thought about it more and this is actually probaly the write functionality for a misshaped packet
