### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by a1cd** [PrismarineJS/flying-squid#515]
I have forked flying squid [to fix an issue that allows players to place blocks inside themselves](https://github.com/a1cd/flying-squid) I have fixed the issue but the test [can place a block](https://github.com/PrismarineJS/flying-squid/blob/73dd100d6f29c9e8b053e6f176da339254df102f/test/mineflayer.test.js#L124) tries to place a block in its own hit box. The test fails. I tried modifying it to place out of the hitbox.

**Comment by u9g** [comment]
have you tried moving the block out further? another approach is that you go and see what is happening in game

**Comment by a1cd** [comment]
Yep I have tried that

How do I join a test world?

**Comment by u9g** [comment]
here: https://github.com/PrismarineJS/flying-squid/blob/73dd100d6f29c9e8b053e6f176da339254df102f/test/mineflayer.test.js#L89
add this code: 
```js
await new Promise((resolve, reject) => {
console.log(`Join now @ localhost:${port}`)
setTimeout(resolve, 20000)
}
```

**Comment by a1cd** [comment]
Ok thanks!
