### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by HrPlanlos** [PrismarineJS/flying-squid#533]
What about TypeScript support? Could not find anything about this and could not install any Types. It is a great support in the development and helps to prevent mistakes and better understand what options you have.

**Comment by hanatic** [comment]
That's a good suggestion. You can technically still run it in TypeScript because it compiles into JS, you just won't get IntelliSense - but I completely agree that this should be implemented.

**Comment by MokiyCodes** [comment]
> That's a good suggestion. You can technically still run it in TypeScript because it compiles into JS, you just won't get IntelliSense - but I completely agree that this should be implemented.

You **can** run it in normal ts, however with
```json
"compilerOptions": {
  "noEmitOnError": true,
  "strict": true
}
```
Typescript will not let you compile it.
