### ISSUE TITLE
What am I doing wrong

### ISSUE THREAD

**Issue by wolfy01** [PrismarineJS/flying-squid#548]
What the heck is this: https://i.imgur.com/xoIUH3U.png 
How am I using it?:
```js
const mcServer = require('flying-squid')

mcServer.createMCServer({
  'motd': 'A Minecraft Server \nRunning flying-squid',
  'port': 25565,
  'max-players': 10,
  'online-mode': true,
  'logging': true,
  'gameMode': 1,
  'difficulty': 1,
  'worldFolder':'world',
  'generation': {
    'name': 'diamond_square',
    'options':{
      'worldHeight': 80
    }
  },
  'kickTimeout': 10000,
  'plugins': {

  },
  'modpe': false,
  'view-distance': 10,
  'player-list-text': {
    'header':'Flying squid',
    'footer':'Test server'
  },
  'everybody-op': true,
  'max-entities': 100,
  'version': '1.16.1'
})
```

**Comment by rom1504** [comment]
what is your image supposed to be?

**Comment by wolfy01** [comment]
> what is your image supposed to be?

I just found out that colors.js is "corrupted". This project isnt the only one affected

**Comment by extremeheat** [comment]
Yes, looks like the owner put in an infinite loop and some log spam but nothing too malicious fortunately. https://github.com/Marak/colors.js/blob/074a0f8ed0c31c35d13d28632bd8a049ff136fb6/lib/index.js#L18

His github/npm account is suspended at least for now but it seems like they won't be removing his perms over the package. So we should definitely replace it with chalk, for now I opened #549 to pin the dep.
