### ISSUE TITLE
Figure out where to store modpe plugins

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#65]
Currently available there http://mcpedl.com/worldedit-pe/
And needs to be manually put in modpePlugins/ dir

**Comment by Creeplays** [comment]
http://www.minecraftforum.net/forums/minecraft-pocket-edition/mcpe-mods-tools

**Comment by Creeplays** [comment]
There is alot of modpe scripts

**Comment by Creeplays** [comment]
But don't all are supported, because of don't full API impl.

**Comment by rom1504** [comment]
Okay interesting. The problem is they store their stuff in mediafire and Dropbox, we can't automatically download from that. Do you think it would be OK to put it in a github repo ?

**Comment by rom1504** [comment]
fixed by f46c4225b54b9c66046cf8b36b1601ae5babbbe6
