### ISSUE TITLE
modpe and async

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#66]
* [x] normal commands
* [x] some misuse of serv.world

**Comment by rom1504** [comment]
well idk if modpe api is implementable with an async representation. That causes bug in the current implementation

**Comment by Creeplays** [comment]
ModPe needs to have returns, patching user scripts to add support for async is impossible.

**Comment by Creeplays** [comment]
- some misuse of serv.world
Explain, I do not understand.

**Comment by roblabla** [comment]
It's possible using deasync for a very stupid, naive implementation that blocks the event-loop.

**Comment by rom1504** [comment]
Yeah, it's written on c++ though, but if modpe is a plugin, I guess that's ok

**Comment by rom1504** [comment]
alright, now you can use [prismarine-world-sync](https://github.com/PrismarineJS/prismarine-world-sync/blob/master/example.js#L26) to implement modpe @Creeplays

**Comment by rom1504** [comment]
@Creeplays ok this is now fixed in 316ed6b49beb17c6d422f3606ba72b7a5e3adb02

I'm not sure how to use world edit though. Can you give a few example of what should work now ?

(all modpe commands are now prefixed by /modpe, so for example "/modpe //sphere 5 5" works, but I don't know what else should work)

**Comment by Creeplays** [comment]
Some scripts will dont work because of not full modpe impl.

**Comment by rom1504** [comment]
Sure. What I am asking is : what works ?

**Comment by rom1504** [comment]
I'm thinking a better way to fix this might be to automatically convert the modpe scripts to make them support the async api. Not sure how hard that would be, maybe not too hard.

**Comment by roblabla** [comment]
@rom1504 well, using something like esprima, you could go through the javascript AST, find the function calls, and try async-ifying them. It'd probably be a bit hard, but not impossible.

**Comment by rom1504** [comment]
Yeah, I think transforming adding await to the function calls (and async to the functions) and then transpiling them with babel might do it.

**Comment by Creeplays** [comment]
Rom, I don't known what version of worldedit you at using. There is alot of it, created by random peoples, and all have antworer function set.

**Comment by rom1504** [comment]
I'm using the one you put on one of your pull request.

https://github.com/Creeplays/flying-squid/blob/e7095a00a977a2fee3ee1698536ff5b28d451cf5/lib/modpePlugins/we.js

**Comment by Creeplays** [comment]
In this we works all, selection are accessible in creative (setItem packet handles only creative) using wooden axe.

**Comment by Creeplays** [comment]
Ticking is not fully working, movePacket = tick for modpe.

**Comment by demipixel** [comment]
Can you explain what you mean?

**Comment by rom1504** [comment]
this was done some time ago

**Comment by rom1504** [comment]
Ah actually, letting it open for "a better way to fix this might be to automatically convert the modpe scripts to make them support the async api"

**Comment by demipixel** [comment]
Now that plugins are done, do we still need this open since it can be made into a plugin?

**Comment by rom1504** [comment]
I'll move it to modpe plugin repo once it's done
