### ISSUE TITLE
modpe should be a plugin

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/flying-squid#69]
It doesn't work so well, and it's hard to maintain, it's probably better if it's not in the main repo.

**Comment by demipixel** [comment]
#32

**Comment by rom1504** [comment]
can be made a plugin now.

**Comment by Creeplays** [comment]
Well, I will rewrite, but how? Modpe is not async.

**Comment by rom1504** [comment]
@Creeplays modpe plugin is now there https://github.com/PrismarineJS/flying-squid-modpe
I can add you there if you want, or you can pr ;)
